---
kind: pipeline
name: ci-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: dependencies
  image: gcc
  volumes:
  - name apt
    path: /usr/local/apt
  commands:
  - apt-get -qq update
  - apt install build-essential meson ninja-build python3-pip python3-setuptools
  - pip3 install --upgrade pip
  - pip3 install meson --user
- name: install
  image: gcc
  commands:
  - mkdir builddir
  - cd builddir
  - meson .. --prefix=/usr/local/apt
  - ninja