kind: pipeline
type: docker
name: ci-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: gcc
  commands:
  - apt-get -qq update
  - apt -y install build-essential meson ninja-build python3-pip python3-setuptools
  - meson builddir
  - ninja -C builddir