langage: c
os: linux
dist: bionic

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:niko2040/e19
  - sudo apt-get -qq update
  - sudo apt-get install -y libefl-dev ninja-build python3-pip python3-setuptools
  - pip3 install --upgrade pip
  - pip3 install meson --user

script:
  - rm -rf builddir && mkdir builddir && cd builddir && meson ..
  - ninja


addons:
  apt:
    update: true
