langage: c
os: linux
dist: bionic
cache: false

env:
  global:
    - LD_LIBRARY_PATH=/opt/efl/lib/x86_64-linux-gnu
    - PKG_CONFIG_PATH=/opt/efl/lib/x86_64-linux-gnu/pkgconfig
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "deHIrHEvvcaXDh8TEux2AgYcFST3GMCWat6uhQeILgfs0DdKgwa2i4sBvsZB1uD/GGKitH/L7AVVlINa6Wf8pf+61FRcwt6GKQV2nDZJD0qzSvxYI7MXWxxxjcrYExnVarIhTI4YSIFCwwQbv22IIaOMSIZ1p+eL0UnsJ8hiBTr8EblKq2vXVRDZ67pOfEvtBzWipy8xVyqHgvkyesyczduoGI5abLZD26gfvgZUE3O0d2MRBDeyGNBVMZMX2ez7Nbm7vVViu3Yfzb1aFkkT/LeCrJFj7WlxmnAT2i1+D7ePaEEZB+TmBbessjDkPAg0oySv7AF5XdIXrMKzJvHJc4GNPYR/3i6cWz7VyQcwq9GnanNSzfxc+IsXzwapp2tB8Lu2efqkEpOfoEgBvVHhEQvNJtj0JKwNsflIM6tOGlQZGnGsvlDUex44JeF+Kn/ALKBwhZAbrtTlXjaEURoA4jARTvKqqbtOBvE4KwDMyURkJxT9nV/7szngrhybwSswypglU7nkIaUiAhWw5AJTI0rjwjT/13s2iOGPMy2RyzCFgVkuo5N+OINZUF66zv7ZoPNbF9ijq1WjJPmEoKIiQyv5w29Eh4kSsmP63SjhjTIp2/N3epOu6xXshE63178rPUnJPrwDlHUDPDRpFg+rp7TgDYTaa71UZL2YHZV85h8="


compiler:
  - clang
  - gcc

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

  - sudo apt-get -qq update
  - sudo apt install build-essential meson ninja-build python3-pip python3-setuptools clang
  - pip3 install --upgrade pip
  - pip3 install meson --user
  - sudo apt install libssl-dev libsystemd-dev libjpeg-dev libglib2.0-dev libgstreamer1.0-dev libluajit-5.1-dev libfreetype6-dev libfontconfig1-dev libfribidi-dev libavahi-client-dev libharfbuzz-dev libibus-1.0-dev libx11-dev libxext-dev libxrender-dev libgl1-mesa-dev libopenjp2-7-dev libwebp-dev libgif-dev libtiff5-dev libpoppler-dev libpoppler-cpp-dev libspectre-dev libraw-dev librsvg2-dev libudev-dev libmount-dev libdbus-1-dev libpulse-dev libsndfile1-dev libxcursor-dev libxcomposite-dev libxinerama-dev libxrandr-dev libxtst-dev libxss-dev libgstreamer-plugins-base1.0-dev libscim-dev libxdamage-dev libwebp-dev libunwind-dev libinput-dev libomp-dev check
  - git clone https://git.enlightenment.org/core/efl.git
  - cd efl
  - mkdir builddir && cd builddir
  - meson .. --prefix=/opt/efl --default-library shared -Dbuild-examples=false -Dbuild-tests=false -Dbindings= -Decore-imf-loaders-disabler='xim','ibus','scim'
  - sudo ninja install
  - cd ../..

script:
  - export PATH=/opt/efl/bin:$PATH
  - rm -rf builddir && mkdir builddir && cd builddir && meson ..
  - ninja


addons:
  apt:
    update: true
  coverity_scan:
    project:
      name: "vtorri/entice"
      description: "Entice image viewer"
    notification_email: vincent.torri@gmail.com
    build_command_prepend: "rm -rf builddir && mkdir builddir && cd builddir && meson .."
    build_command: "ninja"
    branch_pattern: coverity_scan
