langage: c
os: linux
dist: bionic

env:
  global:
    - LD_LIBRARY_PATH=/opt/efl/lib/x86_64-linux-gnu
    - PKG_CONFIG_PATH=/opt/efl/lib/x86_64-linux-gnu/pkgconfig

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt install build-essential meson ninja-build python3-pip python3-setuptools clang
  - pip3 install --upgrade pip
  - pip3 install meson --user
  - sudo apt install libssl-dev libsystemd-dev libjpeg-dev libglib2.0-dev libgstreamer1.0-dev libluajit-5.1-dev libfreetype6-dev libfontconfig1-dev libfribidi-dev libavahi-client-dev libharfbuzz-dev libibus-1.0-dev libx11-dev libxext-dev libxrender-dev libgl1-mesa-dev libopenjp2-7-dev libwebp-dev libgif-dev libtiff5-dev libpoppler-dev libpoppler-cpp-dev libspectre-dev libraw-dev librsvg2-dev libudev-dev libmount-dev libdbus-1-dev libpulse-dev libsndfile1-dev libxcursor-dev libxcomposite-dev libxinerama-dev libxrandr-dev libxtst-dev libxss-dev libgstreamer-plugins-base1.0-dev libscim-dev libxdamage-dev libwebp-dev libunwind-dev libinput-dev libomp-dev check
  - git clone https://git.enlightenment.org/core/efl.git
  - cd efl
  - mkdir builddir && cd builddir
  - meson .. --prefix=/opt/efl --default-library shared -Dbuild-examples=false -Dbuild-tests=false -Dbindings=
  - sudo ninja install
  - cd ..

script:
  - export PATH=/opt/efl/bin:$PATH
  - rm -rf builddir && mkdir builddir && cd builddir && meson ..
  - ninja


addons:
  apt:
    update: true
