name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt install build-essential meson ninja-build python3-pip python3-setuptools
        pip3 install --upgrade pip
        pip3 install meson --user
        sudo apt install libssl-dev libsystemd-dev libjpeg-dev libglib2.0-dev libgstreamer1.0-dev libluajit-5.1-dev libfreetype6-dev libfontconfig1-dev libfribidi-dev libavahi-client-dev libharfbuzz-dev libibus-1.0-dev libx11-dev libxext-dev libxrender-dev libgl1-mesa-dev libopenjp2-7-dev libwebp-dev libgif-dev libtiff5-dev libpoppler-dev libpoppler-cpp-dev libspectre-dev libraw-dev librsvg2-dev libudev-dev libmount-dev libdbus-1-dev libpulse-dev libsndfile1-dev libxcursor-dev libxcomposite-dev libxinerama-dev libxrandr-dev libxtst-dev libxss-dev libgstreamer-plugins-base1.0-dev libscim-dev libxdamage-dev libwebp-dev libunwind-dev libinput-dev
    - name: Install EFL git
      run: |
        git clone https://git.enlightenment.org/core/efl.git
        cd efl
        mkdir builddir
        cd builddir
        meson .. --prefix=/opt/efl --default-library shared -Dbuild-examples=false -Dbuild-tests=false -Dbindings=
        sudo ninja install
    - name: Build Entice
      run: |
        export PATH=/opt/efl/bin:$PATH
        export LD_LIBRARY_PATH=/opt/efl/lib/x86_64-linux-gnu
        export PKG_CONFIG_PATH=/opt/efl/lib/x86_64-linux-gnu/pkgconfig
        mkdir builddir
        cd builddir
        meson .. --prefix=/opt/efl
        ninja
